@startuml context
!include C4_Context.puml

LAYOUT_WITH_LEGEND()

title Context diagram для Система управления проектами (SUP)

Person(project_manager, "Руководитель", "Руководитель отдела")
Person(developer, "Разработчик", "рядовой работник")
Person(administrator, "Администратор", "поддержка")
Person_Ext(tms_user, "Тестировщик", "пользвоатель TMS")

System(SUP, "SUP", "Система управления проектами")

System_Ext(tms, "tms", "Внешняя система тестирования")

Rel(project_manager, SUP, "Назначает роль, ищет пользователя, Создаёт новую задачу, редактирует задачу, меняет статус задачи, Редактирует проект, изменяет участников проекта, Изменяет статус проекта, ищет проект, отправляет уведомления")
Rel_Back(SUP, administrator, "Создаёт проект, редактирует проект, архивирует проект, ищет проект, Проводит манипуляции над системой, Редактирует пользователя, ищет пользователя,добавляет пользователя")
Rel_Back(SUP, developer, "Ищет пользователя, Ищет проект, Создаёт новую задачу, редактирует задачу, меняет статус задачи, подписывается на задачу, ищет задачу")
Rel(tms_user, tms, "Взаимодействует с TMS")
Rel_Neighbor(tms, SUP, "Обновляет информацию в задаче")
@enduml